universe = vanilla
log = log/chtc_$(Cluster).log
error = error/chtc_$(Cluster)_$(infile).err

executable = ./hw4.sh
arguments = cB58_Lyman_break.fit $(infile).tgz
output = output/chtc_$(Cluster)_$(infile).out

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = R.tar.gz, /home/groups/stat679/boss/cB58_Lyman_break.fit, hw4.R, /home/groups/stat679/boss/tgz/$(infile).tgz

request_cpus = 1
request_memory = 1GB
request_disk = 500MB

queue infile from filename1.txt